### ISSUE TITLE
Build fails: 'X11/xshmfence.h' file not found

### ISSUE THREAD

**Issue by maciozo** [DAINRA/ungoogled-chromium-void#10]
I get a build failure when attempting to build `[30603/49606] CXX obj/components/viz/service/gpu_service_dependencies/output_presenter_x11.o` from 7f1c2feb28abeffc0a62681b9bc7266a1a29daa5:

`../../components/viz/service/display_embedder/output_presenter_x11.cc:8:10: fatal error: 'X11/xshmfence.h' file not found`

Linux 5.13.19_1 on x86_64, glibc.

**Comment by DAINRA** [comment]
Yeah getting the same on the latest tree. It broke somewhere in the last 3 days - I suspect it might be related to [this](https://github.com/void-linux/void-packages/commit/7b4119df5cbc0cc37348164a10c88a32910009d8) commit.

**Comment by DAINRA** [comment]
So ... not exactly sure where the break occurs exactly and even going back in the void-packages tree (to a known working commit) doesn't fix it.
I'll start a regular chromium build to see if the same problem persists and either report it to void-packages or look more into it.

**Comment by maciozo** [comment]
For what it's worth, adding `libxshmfence-devel` to `makedepends` let it build successfully, and the browser _seems_ to run fine. Of course, this could mean that some things were not ungoogled.

**Comment by DAINRA** [comment]
Good to know. And about the ungoogling part don't worry, the patches work on the chromium source so unless you had errors in the patching stage it should work as expected.

**Comment by maciozo** [comment]
Five minutes of scrolling up later, it doesn't look like there were any patching errors.

**Comment by DAINRA** [comment]
You could have skipped the log ... xbps-src would have errored with a message like above but in do_patch(). The python scripts from ungoogled-chromium that handle the patching spit out errors and xbps-src stops on any error. :)

**Comment by maciozo** [comment]
I wanted to be sure ;)
