### ISSUE TITLE
Reproducable builds?

### ISSUE THREAD

**Issue by uuuvn** [DAINRA/ungoogled-chromium-void#23]
I just built ungoogled-chromium(musl) from this repository, and the sha256 sums of my build and the official one from the Releases are different. 
A quick diff of the binaries showed that not only the timestamps are different. 
Any plans to do determenistic builds?

**Comment by DAINRA** [comment]
Unfortunately Void's build system is not deterministic so I have no way of providing reproductible builds (even consecutive builds produce different results).
As for the sha256 checksums on the release page, they are just part of the build workflow, I only added them as a check to ensure that the package isn't modified between thee time xbps builds it and the time of the publish.

**Comment by uuuvn** [comment]
Got it, thanks.
