### ISSUE TITLE
x86 glibc compiled Chromium doesn't run on Intel P4/Xeon older hardware

### ISSUE THREAD

**Issue by MechDR** [DAINRA/ungoogled-chromium-void#38]
As the title says, it doesn't run on older SSE/SSE2 only CPUs, like older Xeons and P4s.

```
fish: Job 1, 'ungoogled-chromium' terminated by signal SIGILL (Illegal instruction)
```

I've compiled it in a VM, since it takes forever on these older rigs (on newer hardware, Intel Core i7 4790K) and it runs in the VM, but not on these old rigs :-\\.

Also, is there a way ninja to use all available CPU cores/threads? Currently, no matter what I compile Ungoogled Chromium on, it always uses 25% of the CPU resources.

**Comment by DAINRA** [comment]
Not too sure about the cpu support, I think chromium only supports cpu's with SSE3 (most cpu's from 2005 till now have it) and up (don't quote me on that ^.^ read it a few years back). Anyway upstream dropped / is dropping support so nut moch to be done.
For ninja try setting `XBPS_MAKEJOBS=2` (replace 2 with the number of cores) in void-packages/etc/conf. Don't know why it's only using on core for you, by default on the laptop I use to compile the releases xbps-src just blasts away on both cores and threads (I use XBPS_MAKEJOBS to limit the cpu & memory load tough that only works for ninja).

**Comment by MechDR** [comment]
> Not too sure about the cpu support, I think chromium only supports cpu's with SSE3 (most cpu's from 2005 till now have it) and up (don't quote me on that ^.^ read it a few years back). Anyway upstream dropped / is dropping support so not much to be done.

Currently compiling on a dual Xeon HP Workstation xw8000, well see if it runs on this thing...

> Edit: 2014 around v35 the dropped support for anything under SSE2, and they started dropping support for SSE2 in chrome v89 (ref: https://www.techradar.com/news/google-chrome-will-no-longer-support-some-older-processors).

Damn :-\\... oh well, we'll see, maybe compiling on this old rig will have some "magical" effect :D.

I'm gonna start from scratch though, it only uses one thread out of 4 available (the Xeon's are with HT), it really does take forever, it's been running for a week now xD.

If it does somehow magically work, I'm sharing them for sure xD.

> For ninja try setting `XBPS_MAKEJOBS=2` (replace 2 with the number of cores) in void-packages/etc/conf. Don't know why it's only using on core for you, by default on the laptop I use to compile the releases xbps-src just blasts away on both cores and threads (I use XBPS_MAKEJOBS to limit the cpu & memory load tough that only works for ninja).

Thanks, will try that :).

Don't know why it only uses 2 threads... maybe because the hardware is really old and can't actually correctly read the number of available threads, so it does a "safe bet, use 25% of whatever is available". I know a lot of legacy code in the kernel has been dropped the past few years, maybe that's why, who knows.

Once again, thanks for the info and suggestions, will try and report with results ;).

**Comment by DAINRA** [comment]
As a tip you should try to use the official method for void instead of a vm (https://github.com/void-linux/void-packages#building-32bit) (take a look at the workflow file for github actions in my repo, it's set up to compile that way).

**Comment by MechDR** [comment]
Mhm, mhm, OK, will take a look ;).

**Comment by MechDR** [comment]
> P.S. ninja is weird sometimes, by default it should also take momory into account (for chrome should be around 2gb / core) as well as cpu, but on my laptop even if i have 2 cores (4 threads) & 4gb ram it is still happy to do 4 threads (hence why i limit it :)).

So, I define the number of cores, not threads, correct? Ninja should pick up if the CPU has HT or not, right?

The RAM might be problem though, the rig has only 1GB of RAM xD. It has to be ECC, that's all the DDR1 ECC RAM I had xD. I have a page file set up for up to 4GB, I hope it will be enough xD.

**Comment by DAINRA** [comment]
It's better that way, the void buildbot also does it that way, and there is no difference from actually compiling on native hardware (and you remove the overhead of the vm).

Anyway my bet is that even if it compiles without errors (the build might actually fail if the compiler is smart enough), the end result will be the same. ~~One more thing I can suggest is look at Debian's repository they might have some related patches.~~ Scratch that it has a won\t fix >.> (ref: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1010407)

**Comment by MechDR** [comment]
> It's better that way, the void buildbot also does it that way, and there is no difference from actually compiling on native hardware (and you remove the overhead of the vm).

OK, trying with `XBPS_MAKEJOBS=2` ATM, we'll see how things go ;).

It takes a while on these rigs to get to building objects, so we'll know in about 30 minutes or so xD.

> Anyway my bet is that even if it compiles without errors (the build might actually fail if the compiler is smart enough), the end result will be the same. ~One more thing I can suggest is look at Debian's repository they might have some related patches.~ Scratch that it has a won\t fix >.> (ref: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1010407)

Hahahaha xD. Outta luck with Chromium on these old rigs xD.

Oh well, might try it just for fun ;). A waste of electricity, but I'm really interested at what the end result will be :).

**Comment by DAINRA** [comment]
>It takes a while on these rigs to get to building objects, so we'll know in about 30 minutes or so xD.

On the current laptop (i5-4210U 4gb ram) the releases in my repo take around 30h each on major versions :).

**Comment by DAINRA** [comment]
In any case, you should leave at least 1 thread unused for the system to use, and ofc consider ram (i've had my machine go to full ram usage and the only thing to do is either hard reset or wait a few hours for the queue to clear >.>).

**Comment by MechDR** [comment]
SSDs and large page files are sorta the solution when it comes to not enough RAM for large compiling tasks like these... or compressing huge amounts of data with LZMA or something similar.

> In the case of big builds that rule from gentoo is good to follow since it optimizes the build (setting the threads too high just bottlenecks the cpu and you get slower times).

Hm, this is good to know, I'll remember this ;).

I set `XBPS_MAKEJOBS=` to 4 xD, it's starting to sweat now xD.

![SHOT001](https://user-images.githubusercontent.com/45944962/196734128-2373fad0-45ee-4c76-a77f-69bad6482846.png)

**Comment by DAINRA** [comment]
https://wiki.gentoo.org/wiki/MAKEOPTS

https://blogs.gentoo.org/ago/2013/01/14/makeopts-jcore-1-is-not-the-best-optimization/

:)

**Comment by MechDR** [comment]
God, I would never survive on a purely source based distro like Gentoo xD.

Will read though, good practices for any distro ;).

**Comment by DAINRA** [comment]
Imo gentoo is good as a learning experience, but in day to day use, performance gains from -O2 optimizations (void) vs -O2 -march=native (gentoo recommended stable) are minimal and not worth the hassle (hell at the end of the day even debian is fast enough if you do a minimal bootstrap install and build on top of that ^_^).

**Comment by MechDR** [comment]
Agreed, people need to get on with their lives, not everyone is into recompiling stuff for 1, 2% gain in performance. Tech crowds, yeah, but even I don't have as much free time as I used to have, so I just use whatever fulfills my needs on a daily basis (that's Ubuntu most of the time, since it's got stuff prepacked with it, I just don't have the time to do `apt get install xxx` for every single library and application I might need).

That being said, I do enjoy tinkering from time to time, mostly with older hardware (it's either free or cheap xD), so currently, this is kinda my "pet project"... not that it will amount to anything, just interested in the end result ;).

**Comment by MechDR** [comment]
Hm, this seems interesting.

https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1921187/comments/15

> Hello, this bug also affects me. I get "Illegal instruction (core dumped)" in console if I try to start Chromium 89. I think it happens because chromium has added requirement for SSE3 in their compile flags (they added "-msse3" in build/config/compiler/BUILD.gn file), so it doesn't start on CPUs without SSE3. On Windows Chrome's updater checks for SSE3 support and doesn't update you past version 88 in this case, but on Ubuntu it got updated anyway.
Here's relevant Chromium changes:
https://bugs.chromium.org/p/chromium/issues/detail?id=1123353
https://chromium-review.googlesource.com/c/chromium/src/+/2311044

Could you make a version of the template that removes `-msse3` from `build/config/compiler/BUILD.gn`? It would be interesting what the end result would be. I'll compile it in the VM, will probably take a day or so ;).

**Comment by DAINRA** [comment]
> Hm, this seems interesting.
> 
> https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1921187/comments/15
> 
> > Hello, this bug also affects me. I get "Illegal instruction (core dumped)" in console if I try to start Chromium 89. I think it happens because chromium has added requirement for SSE3 in their compile flags (they added "-msse3" in build/config/compiler/BUILD.gn file), so it doesn't start on CPUs without SSE3. On Windows Chrome's updater checks for SSE3 support and doesn't update you past version 88 in this case, but on Ubuntu it got updated anyway.
> > Here's relevant Chromium changes:
> > https://bugs.chromium.org/p/chromium/issues/detail?id=1123353
> > https://chromium-review.googlesource.com/c/chromium/src/+/2311044
> 
> Could you make a version of the template that removes `-msse3` from `build/config/compiler/BUILD.gn`? It would be interesting what the end result would be. I'll compile it in the VM, will probably take a day or so ;).
>
> EDIT: Never mind, I just added this after line 88 in the template file.
> 
> ```
> # Disable SSE3 requirement when building, use only SSE2
> sed -i 's/"-msse3",/"-msse2",/g' \
> 	build/config/linux/BUILD.gn
> ```

That might work for now, but in the long run you will wind up needing custom patches (for ref: [chromium-no-sse2-patch)](https://github.com/bircoph/chromium-no-sse2-patch)).  
That said, if there is a patchset that is well mentained, I'll add it to the readme, but as far as the template is concerned I'll be keeping it close to the void one (mostly because of lack of time, like I said atm it takes me about 60h to compile a release for both x86 and x86-musl binaries and that leaves no room for extensive testing - sorry :( ).

**Comment by MechDR** [comment]
> That might work for now, but in the long run you will wind up needing custom patches (for ref: [chromium-no-sse2-patch)](https://github.com/bircoph/chromium-no-sse2-patch)). That said, if there is a patchset that is well mentained, I'll add it to the readme, but as far as the template is concerned I'll be keeping it close to the void one (mostly because of lack of time, like I said atm it takes me about 60h to compile a release for both x86 and x86-musl binaries and that leaves no room for extensive testing - sorry :( ).

Yeah, sure, no prob ;), I'll probably just clone your repo and make the adequate changes for the custom builds and build only for x86 and x86-musl... and maybe other architectures if anyone asks, but no x64 releases, I'll leave that to you :D. Besides, I don't believe there is an x64 capable CPU out there that doesn't support SSE3, but, if there is and there's no other way, I'll make x64 SSE2 only builds as well, no prob :). I might not maintain them for every new version, but a new version every month or so is pretty consistent IMO... in any case, it's a lot better than what is being served now xD.

Now, I've compiled it over the weekend, let's see what happens :).

Nope, doesn't work :(.

`fish: Job 1, 'ungoogled-chromium' terminated by signal SIGILL (Illegal instruction)`

Though it seems like it's doing a lot more than the previous build, with SSE3, but in the end, it needs more patching :-\\.
