### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by costowell** [DAINRA/ungoogled-chromium-void#45]
As of the last week, I keep getting this error about an invalid signature. Not sure if anyone else is experiencing this or if I did something to make it happen.
![image](https://user-images.githubusercontent.com/121599022/218333458-1016cb05-e471-4eed-b5db-efafe902ab3e.png)

**Comment by DAINRA** [comment]
Should be fixed now, I updated the repodata and signatures.
Long story short, I bought a new machine for building and during testing forgot to sign the repodata (the workflow for building the releases only signs the packages xD).

**Comment by costowell** [comment]
Hahaha awesome, thank you it works!
