### ISSUE TITLE
Signature error when installing ungoogled chromium 112

### ISSUE THREAD

**Issue by gorhatlin** [DAINRA/ungoogled-chromium-void#50]
[*] Downloading packages
ungoogled-chromium-112.0.5615.49_1.x86_64.xbps.sig
ungoogled-chromium-112.0.5615.49_1.x86_64.xbps
ungoogled-chromium-112.0.5615.49_1: verifying RSA signature...
ERROR: ungoogled-chromium-112.0.5615.49_1: the RSA signature is not valid!
ERROR: ungoogled-chromium-112.0.5615.49_1: removed pkg archive and its signature.

**Comment by DAINRA** [comment]
Fixed now, I guess xbps-rindex doesn't override existing signatures and it kept some older signatures from the builds I did for ccache generation >_<

**Comment by gorhatlin** [comment]
Yup, it's fixed. Thank you very much.
