### ISSUE TITLE
Unresolvable shlib error when updating

### ISSUE THREAD

**Issue by cy1der** [DAINRA/ungoogled-chromium-void#59]
Hello, I ran the usual `sudo xbps-install -Su` to update my packages and I am hit with this error:

```
ungoogled-chromium-119.0.6045.105_1: broken, unresolvable shlib `libFLAC.so.8'
Transaction aborted due to unresolved shlibs
```

**Comment by DAINRA** [comment]
There was a big rebuild in the weekend for that package and I was waiting for it to be available (xbps-src was complaining about it also). Will push an update after I'm done rebuilding the cache so in about 2-3 hours.
